// Code generated by go-swagger; DO NOT EDIT.

package time

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"zenport/gates/gatesclient/models"
)

// GetTimeReader is a Reader for the GetTime structure.
type GetTimeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTimeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTimeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetTimeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetTimeOK creates a GetTimeOK with default headers values
func NewGetTimeOK() *GetTimeOK {
	return &GetTimeOK{}
}

/*
GetTimeOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetTimeOK struct {
	Payload *models.GatespbGetTimeResponse
}

// IsSuccess returns true when this get time o k response has a 2xx status code
func (o *GetTimeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get time o k response has a 3xx status code
func (o *GetTimeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get time o k response has a 4xx status code
func (o *GetTimeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get time o k response has a 5xx status code
func (o *GetTimeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get time o k response a status code equal to that given
func (o *GetTimeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get time o k response
func (o *GetTimeOK) Code() int {
	return 200
}

func (o *GetTimeOK) Error() string {
	return fmt.Sprintf("[POST /api/times][%d] getTimeOK  %+v", 200, o.Payload)
}

func (o *GetTimeOK) String() string {
	return fmt.Sprintf("[POST /api/times][%d] getTimeOK  %+v", 200, o.Payload)
}

func (o *GetTimeOK) GetPayload() *models.GatespbGetTimeResponse {
	return o.Payload
}

func (o *GetTimeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatespbGetTimeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTimeDefault creates a GetTimeDefault with default headers values
func NewGetTimeDefault(code int) *GetTimeDefault {
	return &GetTimeDefault{
		_statusCode: code,
	}
}

/*
GetTimeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetTimeDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this get time default response has a 2xx status code
func (o *GetTimeDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get time default response has a 3xx status code
func (o *GetTimeDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get time default response has a 4xx status code
func (o *GetTimeDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get time default response has a 5xx status code
func (o *GetTimeDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get time default response a status code equal to that given
func (o *GetTimeDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get time default response
func (o *GetTimeDefault) Code() int {
	return o._statusCode
}

func (o *GetTimeDefault) Error() string {
	return fmt.Sprintf("[POST /api/times][%d] getTime default  %+v", o._statusCode, o.Payload)
}

func (o *GetTimeDefault) String() string {
	return fmt.Sprintf("[POST /api/times][%d] getTime default  %+v", o._statusCode, o.Payload)
}

func (o *GetTimeDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GetTimeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
