// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: gatespb/api.proto

package gatespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GatesServiceClient is the client API for GatesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatesServiceClient interface {
	GetTime(ctx context.Context, in *GetTimeRequest, opts ...grpc.CallOption) (*GetTimeResponse, error)
}

type gatesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatesServiceClient(cc grpc.ClientConnInterface) GatesServiceClient {
	return &gatesServiceClient{cc}
}

func (c *gatesServiceClient) GetTime(ctx context.Context, in *GetTimeRequest, opts ...grpc.CallOption) (*GetTimeResponse, error) {
	out := new(GetTimeResponse)
	err := c.cc.Invoke(ctx, "/gatespb.GatesService/GetTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatesServiceServer is the server API for GatesService service.
// All implementations must embed UnimplementedGatesServiceServer
// for forward compatibility
type GatesServiceServer interface {
	GetTime(context.Context, *GetTimeRequest) (*GetTimeResponse, error)
	mustEmbedUnimplementedGatesServiceServer()
}

// UnimplementedGatesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatesServiceServer struct {
}

func (UnimplementedGatesServiceServer) GetTime(context.Context, *GetTimeRequest) (*GetTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTime not implemented")
}
func (UnimplementedGatesServiceServer) mustEmbedUnimplementedGatesServiceServer() {}

// UnsafeGatesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatesServiceServer will
// result in compilation errors.
type UnsafeGatesServiceServer interface {
	mustEmbedUnimplementedGatesServiceServer()
}

func RegisterGatesServiceServer(s grpc.ServiceRegistrar, srv GatesServiceServer) {
	s.RegisterService(&GatesService_ServiceDesc, srv)
}

func _GatesService_GetTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatesServiceServer).GetTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gatespb.GatesService/GetTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatesServiceServer).GetTime(ctx, req.(*GetTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatesService_ServiceDesc is the grpc.ServiceDesc for GatesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gatespb.GatesService",
	HandlerType: (*GatesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTime",
			Handler:    _GatesService_GetTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gatespb/api.proto",
}
