// Code generated by mockery v2.16.0. DO NOT EDIT.

package gatespb

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockGatesServiceClient is an autogenerated mock type for the GatesServiceClient type
type MockGatesServiceClient struct {
	mock.Mock
}

// GetTime provides a mock function with given fields: ctx, in, opts
func (_m *MockGatesServiceClient) GetTime(ctx context.Context, in *GetTimeRequest, opts ...grpc.CallOption) (*GetTimeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *GetTimeResponse
	if rf, ok := ret.Get(0).(func(context.Context, *GetTimeRequest, ...grpc.CallOption) *GetTimeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetTimeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *GetTimeRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockGatesServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockGatesServiceClient creates a new instance of MockGatesServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGatesServiceClient(t mockConstructorTestingTNewMockGatesServiceClient) *MockGatesServiceClient {
	mock := &MockGatesServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
