// Code generated by mockery v2.16.0. DO NOT EDIT.

package gatespb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeGatesServiceServer is an autogenerated mock type for the UnsafeGatesServiceServer type
type MockUnsafeGatesServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedGatesServiceServer provides a mock function with given fields:
func (_m *MockUnsafeGatesServiceServer) mustEmbedUnimplementedGatesServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewMockUnsafeGatesServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnsafeGatesServiceServer creates a new instance of MockUnsafeGatesServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnsafeGatesServiceServer(t mockConstructorTestingTNewMockUnsafeGatesServiceServer) *MockUnsafeGatesServiceServer {
	mock := &MockUnsafeGatesServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
