// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GatespbGetTimeRequest gatespb get time request
//
// swagger:model gatespbGetTimeRequest
type GatespbGetTimeRequest struct {

	// ask
	Ask string `json:"ask,omitempty"`
}

// Validate validates this gatespb get time request
func (m *GatespbGetTimeRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gatespb get time request based on context it is used
func (m *GatespbGetTimeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GatespbGetTimeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GatespbGetTimeRequest) UnmarshalBinary(b []byte) error {
	var res GatespbGetTimeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
