// Code generated by mockery v2.16.0. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTimeRepository is an autogenerated mock type for the TimeRepository type
type MockTimeRepository struct {
	mock.Mock
}

// Load provides a mock function with given fields: ctx, user
func (_m *MockTimeRepository) Load(ctx context.Context, user string) (*Time, error) {
	ret := _m.Called(ctx, user)

	var r0 *Time
	if rf, ok := ret.Get(0).(func(context.Context, string) *Time); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockTimeRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTimeRepository creates a new instance of MockTimeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTimeRepository(t mockConstructorTestingTNewMockTimeRepository) *MockTimeRepository {
	mock := &MockTimeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
