// Code generated by mockery v2.16.0. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNtpRepository is an autogenerated mock type for the NtpRepository type
type MockNtpRepository struct {
	mock.Mock
}

// FetchTime provides a mock function with given fields: ctx, request
func (_m *MockNtpRepository) FetchTime(ctx context.Context, request string) (string, error) {
	ret := _m.Called(ctx, request)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockNtpRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockNtpRepository creates a new instance of MockNtpRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockNtpRepository(t mockConstructorTestingTNewMockNtpRepository) *MockNtpRepository {
	mock := &MockNtpRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
